version: "3.9"

services:
  google:
    container_name: "carolyn-google"
    restart: always
    build: ./GoogleService
    ports:
      - "5000:5000"
    volumes:
      - ./GoogleService:/app
  telegrambot:
    container_name: "carolyn-telegrambot"
    environment:
      CAROLYN_DEPLOY_ID: ${CAROLYN_DEPLOY_ID}
      CAROLYN_DEPLOY_VERSION: ${CAROLYN_DEPLOY_VERSION}
    restart: always
    build: ./TelegramBot
    volumes:
      - ./TelegramBot:/app
