version: "3.9"

services:
  spreadsheets:
    container_name: "carolyn-spreadsheets"
    restart: always
    build: ./SpreadsheetsService
    ports:
      - "5000:5000"
    volumes:
      - ./SpreadsheetsService:/app
  telegrambot:
    container_name: "carolyn-telegrambot"
    environment:
      - CAROLYN_DEPLOY_ID
      - CAROLYN_DEPLOY_VERSION
    restart: always
    build: ./TelegramBot
    volumes:
      - ./TelegramBot:/app
