version: "3.9"

services:
  spreadsheets:
    container_name: "carolyn-spreadsheets"
    restart: always
    build: ./SpreadsheetsService
    ports:
      - "5000:5000"
    environment:
      SECRETKEY: "HELLO-WORLD-@21XX 15AF"
    volumes:
      - ./SpreadsheetsService:/app
  telegrambot:
    container_name: "carolyn-telegrambot"
    restart: always
    build: ./TelegramBot
    volumes:
      - ./TelegramBot:/app
