name: deploy-to-Yandex-Cloud

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: webfactory/ssh-agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.KEY }}

      - name: Set up keys for Yandex Cloud
        run: |
          echo "${{ secrets.key }}" > "$HOME/key"
          chmod 600 "$HOME/key"

      - name: Restart Bot at Yandex Cloud
        run:
          ssh -i $HOME/key carolyn@${{ secrets.HOST }} -o StrictHostKeyChecking=no
          '
          cd Carolyn &&
          git pull &&
          export CAROLYN_DEPLOY_ID="$(git rev-parse HEAD)" &&
          export CAROLYN_DEPLOY_VERSION="$(git describe --tags)" &&
          docker-compose down &&
          docker-compose up -d
          '
