name: deploy-to-Yandex-Cloud

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: webfactory/ssh-agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.KEY }}

      - name: Set up keys for Yandex Cloud
        run: |
          echo "${{ secrets.key }}" > "$HOME/key"
          chmod 600 "$HOME/key"

      - name: Connect to the Yandex Cloud
          ssh -i $HOME/key carolyn@${{ secrets.HOST }} -o StrictHostKeyChecking=no
          ls -laF
